export const GET_POPULAR_SUCCESS = "GET_POPULAR_SUCCESS";
export const GET_POPULAR_FAILED = "GET_POPULAR_FAILED";

export const GET_LATEST_SUCCESS = "GET_LATEST_SUCCESS";
export const GET_LATEST_FAILED = "GET_LATEST_FAILED";

export const GET_UPCOMING_SUCCESS = "GET_UPCOMING_SUCCESS";
export const GET_UPCOMING_FAILED = "GET_UPCOMING_FAILED";

export const ADD_MOVIE_TO_WATCHLIST = "ADD_MOVIE_TO_WATCHLIST";
export const REMOVE_MOVIE_FROM_WATCHLIST = "REMOVE_MOVIE_FROM_WATCHLIST";

export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAILED = "GET_MOVIE_DETAILS_FAILED";

export const GET_SIMILAR_MOVIES_SUCCESS = "GET_SIMILAR_MOVIES_SUCCESS";
export const GET_SIMILAR_MOVIES_FAILED = "GET_SIMILAR_MOVIES_FAILED";

export const MOVIE_DETAILS_RESET = "MOVIE_DETAILS_RESET";

export const MOVIE_SEARCH_SUCCESS = "MOVIE_SEARCH_SUCCESS";
export const MOVIE_SEARCH_FAILED = "MOVIE_SEARCH_FAILED";

export const SET_QUERY = "SET_QUERY";
export const RESET_SEARCH_LIST = "RESET_SEARCH_LIST";

export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const TOGGLE_NAV = "TOGGLE_NAV";

export const GET_MOVIE_CREDITS_SUCCESS = "GET_MOVIE_CREDITS_SUCCESS";
export const GET_MOVIE_CREDITS_FAILED = "GET_MOVIE_CREDITS_FAILED";
